apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: coffee2k
  annotations:
    trait.camel.apache.org/mount.resources: "configmap:stage4-transform"
    trait.camel.apache.org/mount.configs: "secret:stage4"
spec:

  source:
    properties:
      period: 5000
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: coffee-source
  steps:
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: jslt-action
    properties:
      template: coffee2k.jslt

  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-sink
    properties:
      bootstrapServers: "{{kafka.bootstrapServer}}"
      password: "{{kafka.clientsecret}}"
      topic: "{{kafka.topic}}"
      user: "{{kafka.clientid}}"
