apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bouvier

resources:
- namespace.yaml
- patty-deployment.yaml
- patty-service.yaml
- patty-route.yaml
- selma-deployment.yaml
- selma-service.yaml
- selma-route.yaml
- default-deny-bouvier.yaml
- allow-from-openshift-ingress-bouvier.yaml
- allow-from-bouviers-to-marge-bouvier.yaml
- allow-same-namespace-bouvier.yaml
