apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: coffee2kafka
spec:
  source:
    properties:
      period: 5000
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: coffee-source
  steps:
    - ref: 
        kind: Kamelet
        apiVersion: camel.apache.org/v1alpha1
        name: log-sink
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: slack-sink
        properties:
          token: MY_KAFKA_TOKEN
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-sink
    properties:
      bootstrapServers: ""
      password: ""
      topic: "sk-topic"
      user: ""