---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 3bbeffa2a3e4234b11103f9d6f59494b85bdc8b1
    app.quarkus.io/build-timestamp: 2023-01-11 - 07:12:20 +0000
  labels:
    app.kubernetes.io/name: quarkus-gitop-demo
    app.openshift.io/runtime: quarkus
  name: quarkus-gitop-demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-gitop-demo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 3bbeffa2a3e4234b11103f9d6f59494b85bdc8b1
    app.quarkus.io/build-timestamp: 2023-01-11 - 07:12:20 +0000
  labels:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: quarkus-gitop-demo
  name: quarkus-gitop-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-gitop-demo
  template:
    metadata:
      labels:
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: quarkus-gitop-demo
    spec:
      containers:
        - image: quay.io/skraft/quarkus-gitop-demo:4.0
          imagePullPolicy: Always
          name: quarkus-gitop-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 3bbeffa2a3e4234b11103f9d6f59494b85bdc8b1
    app.quarkus.io/build-timestamp: 2023-01-11 - 07:12:20 +0000
  labels:
    app.kubernetes.io/name: quarkus-gitop-demo
    app.openshift.io/runtime: quarkus
  name: quarkus-gitop-demo
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: quarkus-gitop-demo
