apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: k2s
  annotations:
    trait.camel.apache.org/mount.resources: "configmap:stage3-transform"
    trait.camel.apache.org/mount.configs: "secret:stage3"
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-source
    properties:
      bootstrapServers: "sk-kafka-cfh-oa-p-kjaq-tmm--a.bf2.kafka.rhcloud.com:443"
      password: "aLCbUN5p4fS9e49hDq5RhWyUvvOo5RJP"
      topic: "sk-topic"
      user: "48dea32f-0fc8-4f3a-bfbe-c90b7235bcf1"

  steps:
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: predicate-filter-action
    properties:  
      expression: $.source != "slack"
      
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: jslt-action
    properties:
      template: k2s.jslt

  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: slack-sink
    properties:
      token: "{{slack.token}}"