apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hacker
    app.kubernetes.io/component: hacker
    app.kubernetes.io/instance: hacker
    app.kubernetes.io/name: hacker
    app.kubernetes.io/part-of: hacker
    app.openshift.io/runtime: redhat
  name: hacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hacker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacker
        deployment: hacker
    spec:
      containers:
      - image: quay.io/openshift-examples/simple-http-server:master
        imagePullPolicy: IfNotPresent
        name: http-server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
